services:
  frontend:
    platform: linux/arm64
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
    container_name: appointment-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mern

  backend:
    platform: linux/arm64
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: appointment-backend
    env_file:
      - ./backend/.env
    ports:
      - "8081:8081"
    networks:
      - mern

networks:
  mern:
    driver: bridge
